[package]
name = "example-contract"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
js-sys = "0.3.61"
serde = "1.0.174"
serde-wasm-bindgen = "0.5.0"
warp-contracts = "0.1.3"
wasm-bindgen = "0.2.84"
wasm-bindgen-futures = "0.4.34"
